### ISSUE TITLE
Issue with audios

### ISSUE THREAD

**Issue by ThatScottishOwl** [Squishy6094/character-select-coop#13]
everytime I get a new character mod w audio it works right? The audio for some reason doesn't. Mario, Luigi, Wario, etc main cast works just fine but there's an issue SPECIFICALLY with the audio mods made by other people, did something happen to the files, am I missing something? Is there a mod to give you sounds? I've seen other people comment on this through other sites, please do give us an update as to how that can be resolved, if it can be. ((By the way it has only happened to certain people, as I can join someone's server and the audio will be just fine with other modded characters))

**Comment by Squishy6094** [comment]
We've been looking into audio issues throughout the development of Character Select v1.10 and most people have sourced the issue at an older version of Extra Characters. This has since been fixed and you can find a new version [here](https://mods.sm64coopdx.com/mods/official-cs-extra-characters-ultimate-pack.342/). If you have any more specifications on this issue I would love to help out! Also apologies for the late response as Github did not notify me of this issue
