### ISSUE TITLE
The game freezes when i jump

### ISSUE THREAD

**Issue by CMDSKIDD** [Squishy6094/character-select-coop#4]
So when I put a character the game freezes when I jump or do any action

**Comment by Agent-11** [comment]
You shouldn't jump.

**Comment by CMDSKIDD** [comment]
Where is the option menú?

**Comment by MlopsFunny** [comment]
Press Z on the character select menu

**Comment by Squishy6094** [comment]
> Where is the option menú?

Open the menu with whatever method you like (If you haven't configured anything, use "/char-select"). Then press the Start Button to pull up the Options Menu. From here you can scroll down to "Custom Voices" and toggle it Off

This won't be required in the future due to sm64ex-coop v37 supposedly having a separate audio system that will be more compatible with alternative devices

Hope this helps! >.<
